// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aihgcdxhweaeoergilyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpaGdjZHhod2VhZW9lcmdpbHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTQ4NDEsImV4cCI6MjA3NDczMDg0MX0.AkBLoDHr8GHBXLXAP4yzLMVaRa_zSohyxxXOcjuux1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});